### ISSUE TITLE
Funkcionalis specifikacio dokumentacio githubra

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-main#1]
A meglevo funkcionalis specifikaciot markdown formatumban fel kellene tenni githubra.

**Comment by jmarton** [comment]
Ezt a taskot kérem, hogy vegye magához valaki (és jelölje is az issue-ban a hozzárendelést)! Ezután lesznek jól követhetőek a véglegesítés során keletkező változások.

A funk.spec helye az szglab5-main repo docs/funkcionalis-specifikacio.md fájlja.

**Comment by davidbolla** [comment]
ma este felrakom

**Comment by davidbolla** [comment]
külön mappába raktam, mert a képek is felmentek. remélem ez nem probléma, ha máshogy szerettétek volna még a sima fájlt meghagytam.

**Comment by jmarton** [comment]
@bkopy, ha késznek tekinted a konverziót, akkor kérlek, zárd az issue-t.

**Comment by gbence** [comment]
https://github.com/bme-db-lab/szglab5-main/tree/bence-functional-specification/docs/funkcionalis-specifikacio << ha ez elfogadható számotokra, akkor légyszi jelezzétek és merge-öljétek...

**Comment by gbence** [comment]
Megtaláltam a PR gombot is. :D

**Comment by lordblendi** [comment]
A feladatlap generalo beepitese kimaradt a specifikaciobol. Illetve a meresvezeto helyettesitese is hianyzik. @eroslevi Levente, kerlek a merge-t, es a kiegeszitest csinald meg!

**Comment by eroslevi** [comment]
Done

**Comment by lordblendi** [comment]
@eroslevi 
Szerintem javitonal nem lejart hatarideju jegyzokonyveknek nem kellene megjelenniuk. Errol mi a velemenyed? Ezzel elkerulhetnenk azt, hogy nem a legutolso jkv-et ertekelik a javitok (ahogy ez tobbszor elofordult mar).

Masik kerdes: latszodjon a laborvezeto szamara a nem veglegesitett jkv ertekeles? Mert ugye a regi rendszerben ezt nem lehet megkulonboztetni, igy nem vegleges ertekelesre kapott par hallgato jegyet az elmult evekben. Szerintem akar az is eleg lenne, hogy "A jkv ertekelese folyamatban", amint egy javito lefoglalta azt. Ehhez mit szolsz?

**Comment by jmarton** [comment]
A két nyitott kérdésből csináltam issue-t. Egyébként késznek tekintem és lezárom. Ha valami felmerül, majd külön issue-ban kezeljük.
