### ISSUE TITLE
jenkins git összekötés

### ISSUE THREAD

**Issue by davidbolla** [bme-db-lab/szglab5-main#11]
http://stackoverflow.com/questions/5212304/authenticate-jenkins-ci-for-github-private-repository

**Comment by szaszm** [comment]
Mivel a repositoryk publikusak, ezért nincs szükség deployment key-re, hanem bármilyen kulccsal le tudja tölteni a jenkins a forrásokat. Beállítottam valahogy, de nem értek annyira a Jenkinshez, hogy ki is tudjam próbálni. Rá tudnál nézni, @bkopy ? Nekem jónak tűnik.

**Comment by davidbolla** [comment]
ahogy megbeszéltük pénteken megoldjuk ezt a problémát :)

**Comment by szaszm** [comment]
A git clone működik, lezárom.
