### ISSUE TITLE
Seed adatok a demohoz

### ISSUE THREAD

**Issue by mdaniszabo** [bme-db-lab/szglab5-main#12]
Sziasztok!

Arra kérnék minden csapatból legalább egy embert, hogy írja le röviden milyen elvárásai vannak adatok szempontjából a demora. Pl milyen típusú adatból nagyságrendileg mennyi kell, illetve ha van konkrét seed adatra elvárás (pl konkrét felhasználó saját névvel és pass-al) akkor azt is kérlek itt jelezzétek.

Ha bizonytalanok vagytok, hogy mit is használtok, nézzétek meg az [ER](https://github.com/bme-db-lab/szglab5-main/blob/master/docs/ER/ER.pdf)-t, vagy kérdezzetek nyugodtan. (Akár itt, akár slacken, ma egész nap elérhető vagyok.)

**Comment by csutorasr** [comment]
Szia!

* student : 12345
* demonstrator : 12345
* admin : 12345
* corrector : 12345

Itt mindenki a sajat nevenek megfelelo jogosultsaggal.

Ezekhez kene labor, aminek a hatarideje lejart, aminek meg tart jelenleg (ebbol is elkezdett es nem elkezdett). Ezt a diakhoz es a demonstratorhoz is hozzakotni.

Legyen minden felhasznalonak emailje, studentnek neptunja, tehat minden esszeu hozza kotheto adat alapbol beallitva.

**Comment by davidbolla** [comment]
mailcím az lenne a legjobb ha <role>@db.bme.hu vagyis: student@db.bme.hu demonstrator@db.bme.hu admin@db.bme.hu corrector@db.bme.hu

köszönöm

**Comment by mdaniszabo** [comment]
Feltöltöttem a demo.seed.json-t a backend repora.
Kérnék minden érintettet, hogy ellenőrizze le megfelel-e az elvárásainak.

**Comment by csutorasr** [comment]
Modositva megfelel most mar.
