### ISSUE TITLE
User storyk

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-main#6]
Kedves Hallgatok!

@eroslevi befejezte a specifikacio veglegesiteset, melyet itt talaltok. https://github.com/bme-db-lab/szglab5-main/tree/dev/docs/funkcionalis-specifikacio

Keri, hogy kezdjetek el a user storyk kidolgozasat, valamint az ER es a specifikacio osszeveteset, hogy mindenre figyeltunk-e az ER-nel.

**Comment by zsambek** [comment]
holnapi nap neki is kezdek!

**Comment by jmarton** [comment]
@zsambek ebből született doksi?

**Comment by csutorasr** [comment]
@jmarton Szerintem egy doksi nem, de mindent figyelembe vettunk az implementaciokor.

**Comment by jmarton** [comment]
OK, akkor köszönettel lezárom.
