### ISSUE TITLE
Telepítési dokumentáció a repoba

### ISSUE THREAD

**Issue by szaszm** [bme-db-lab/szglab5-main#7]
A félkész telepítési dokumentációt át kellene nézni, és migrálni a szglab5-main repoba. A dokumentum jelenlegi állapota erősen draft, itt olvasható:
https://docs.google.com/document/d/1WN97dBTWXL5iOhhvpZZqGAOdQGsWKJH_Z21kh_gE4tk/edit?usp=sharing

**Comment by szaszm** [comment]
@jmarton: Megfelel így, vagy változtassak rajta?

**Comment by jmarton** [comment]
@szaszm majdnem jó. Két kérésem van:

 1. a docs/install/README.md helyre kerüljön
 2. készíts a docs/uzemeltetes/README.md helyre üzemeltetési leírást. Egyelőre egy dolog kell bele: hogyan történik az alkalmazás frissítések telepítése
