### ISSUE TITLE
Init fajlok

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-main#8]
@Kisfejes keresere felraktam ket fajlt ide, amik tartalmazzak a feleves adatokat - tesztadatokkal feltoltve.
https://github.com/bme-db-lab/szglab5-main/tree/master/docs/init-templates

Viszont: sem a fajlok, sem a fajlokban levo munkalapon nem szoktak egyszerre elkeszulni, ezek folyamatosan update-lesre kerulnek @gajdos altal. Ugyhogy a pontos sorrendrol ot tudjatok kerdezni.

**Comment by jmarton** [comment]
Az inicializálás 2017. ősszel működött.
