### ISSUE TITLE
ER kérdések - hallgató méréssel kapcsolatos funkciói

### ISSUE THREAD

**Issue by markfejes** [bme-db-lab/szglab5-main#9]
Az lenne a kérdésem, hogy a következő mezők az ER-ben minek felelnek meg (innen: https://github.com/bme-db-lab/szglab5-backend/issues/24).

* Kezdeti jelszavak megtekintése
* Labor jegy lekérdezése
* Labor riport lekérdezése
* Értékelt Git címke lekérdezése

**Comment by lordblendi** [comment]
Kezdeti jelszavak szerintem eddig nem tarolodtak az adatbazisban, es most sem terveztuk, hogy benne legyenek. @jmarton tud szerintem arrol tobbet mondani nektek, hogy most ez hogy mukodik.

Laborjegy es laborriport az 1 Deliverables, ugyanugy, mint a [jkv jegy, jkv riport] paros, illetve a beugrojegy (itt ugye nincs riport).

Mit ertesz Git cimke alatt? A git url elerheto a Repositories-on keresztul (egy Deliverables, ami Repositories), utana a tageket es a commitokat a git szervertol kellene lekernetek.

**Comment by markfejes** [comment]
> Laborjegy es laborriport az 1 Deliverables, ugyanugy, mint a [jkv jegy, jkv riport] paros, illetve a beugrojegy (itt ugye nincs riport).

Akkor nekem nem egészen világos ez a rész.
A https://github.com/bme-db-lab/szglab5-main/tree/master/docs/ER leírás alapján:

> A beugró eredménye is egy deliverable (az általános Deliverable egyede), és pl. a git-es beadandó egy RepositoryDeliverable. Ezért a Deliverables es a DeliverableTemplate az tenyleg kell. Pl. a SOA mérés EventTemplate-jához felvesszük, hogy tartozik két DeliverableTemplate: 1. beugró, 2. egy git repo. Ez alapján legeneráljuk az adott EVent példányokhoz a Deliverable példányokat.

Akkor lesz még egy DeliverableTemplate (labor), ami ugyanúgy kapcsolódik az Event-hez?

> Mit ertesz Git cimke alatt? A git url elerheto a Repositories-on keresztul (egy Deliverables, ami Repositories), utana a tageket es a commitokat a git szervertol kellene lekernetek.

Az oké hogy az url megvan, de ha jól értem a dolgokat, akkor szükség van egy git tag-re, ami azonosít egy commit-ot a repo-ban ami alapján elkészült az értékelés.

**Comment by lordblendi** [comment]
> Akkor lesz még egy DeliverableTemplate (labor), ami ugyanúgy kapcsolódik az Event-hez?

Igen.

> Az oké hogy az url megvan, de ha jól értem a dolgokat, akkor szükség van egy git tag-re, ami azonosít egy commit-ot a repo-ban ami alapján elkészült az értékelés.

Nem teljesen, mert olyan commitot is ki kell tudni listazni, amin nincs tag. Inkabb egy Commit kene, amihez  opcionalisan tartozhat tag is. Frontend oldalon majd ilyesminek kellene megjelennie:

- branch1/commithash1
- branch1/commithash0
- branch2/commithash1
- branch2/commithash2 (TAG: tag1)

**Comment by jmarton** [comment]
kezdeti jelszavak: szedjük össze, hogy milyen jelszavakról lehet szó a tárgy során.

1. laboradmin jelszó: ezt leginkább valami jelszó reset mechanizmuson keresztül kellene kiosztani (email cím ismeretében). A címtáras azonosítás miatt a hallgatók ezt nem használnák (de nem is akarjuk tiltani a funkciót), mivel a félév kezdetén még nem tudjuk az email címüket (a neptunkódos email címzést ha nem muszáj, ne használjuk).
2. linux shell szerver: nyilvános kulccsal menne a belépés
3. adatbázisjelszó: ezt nem kell sehol sem tárolni
4. gitlab jelszó: jelszó reset mechanizmuson keresztül (ha egyáltalán használja valaki, és nem elég neki az ssh kulcs)

Ha nem hagytam ki semmit, akkor nincs szükség cleartext jelszavak tárolására és a kezdeti jelszó megtekintésére sem, kihúzható a use case. A jelenben (1) és (2) jelszó kiosztása a mérésen, nyomtatva történik.

**Comment by jmarton** [comment]
@Kisfejes Commit/tag kérdése: beszéltünk róla az imént @lordblendi -vel, és arra jutottunk, hogy maradjunk a csak tag-ek listázásánál. Tárolni már a commit hash (vagy a commit hash-t is) kellene.

Ennek megfelelően a kliens a tagek mellett a commit hash-t, időbélyeget és a commit üzenetet kapja meg, és ezt listázza valahogy a beadáshoz. A branch nevére nincs szükség (főleg hogy a gitlab tag API sem adja vissza)

Gitlab-on Developer jogosultsággal nincs lehetőség a tag módosítására, ezt ki fogjuk használni. Így bár a master branchet át tudja írni, aki akarja, de akkor is a tagjét értékeljük. Mivel a tag ott van, egy "git gc" sem fogja eltüntetni a taggelt commitot.
